### ISSUE TITLE
Grabbable under Grab Block doesn't show red lasers.

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1646]
## Describe the bug
I am trying to make an object that is placeable in a world such that it can be picked up again later, but only some parts of the object act as 'handles'. Grab Block works fine for this, handles outside of the block and the content inside of the block, however items inside  the non-handle section may still be grabbable things.
This also works programmatically, I can still grab things inside the grab block when that object itself has a grabbable component, however the user's laser shows up as white instead of red when hovering over the sub-grabbable object.

## To Reproduce
Have an object that is grabbable parented under a grab block.

## Expected behavior
The laser is shown as red instead of white when cursoring over the grabbable object.

## Screenshots / Video
![Photo in Neos Home Exploration](https://user-images.githubusercontent.com/1251609/105616522-96b23c80-5d8c-11eb-933a-5b88a06274e5.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.1.22.1352
 - Neos Platform: Windows
 - Link to reproduction World/Item: [Optional, but can speed up response for more complex reproduction cases]
 - Regression: Unknown, first time seeing or did not notice before.

## Additional context
The functionality is intact, it's just visually not showing up correctly.

## Reporters:
Earthmark#0314

**Comment by shiftyscales** [comment]
Seems related to #1359 @Earthmark.

**Comment by Earthmark** [comment]
More than likely! I only searched open, my bad

**Comment by Frooxius** [comment]
Should be fixed in 2021.1.24.1266, thanks for report!

**Comment by Earthmark** [comment]
As of 2021.1.24.1327 this is still an issue, I can link an item to demonstrate if requested
