### ISSUE TITLE
Laser gripping a CharacterParenter shifts the parented user's position/view

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1705]
## Describe the bug
A user that is under a CharacterParenter will have their position/view shifted if another user grips the CharacterParenter object with their laser.

## To Reproduce
- Have a user enter a CharacterParenter
- Have another user grab the CharacterParenter

## Expected behavior
The parented user should remain in the same position/rotation, and their viewpoint should stay consistent.

## Screenshots / Video
https://cdn.discordapp.com/attachments/515553786102546442/806442007588896798/2021-02-03_00-31-10.mp4
https://cdn.discordapp.com/attachments/515553786102546442/806445085185146950/2021-02-03_00-44-10.mp4

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.1.29.612
 - Neos Platform: Windows
 - Regression: No

## Additional context
> "I see thanks! Hmm, my guess it it might have something to do with the laser stream perhaps, which synchronizes the position of the held items."
- It appears the size of the collider may play a factor, as possibly does the user's position relative to their user root
- A larger collider was less likely to drop the user, whereas a smaller one was more likely to do so, particualrly if the user was standing towards the edge of the CharacterParenter's volume
- This issue is pretty niche, hence not currently a high priority

## Reporters:
Shifty# 7944, Turk# 2971, ohzee# 2709

**Comment by Frooxius** [comment]
Can you check if this is potentially fixed with 2021.2.4.348? I haven't looked into this one, just wondering if it had something to do with the invalid values/math.

**Comment by shiftyscales** [comment]
It appears this is still an issue on the current build 2021.2.4.348, @Frooxius
