### ISSUE TITLE
[Bug] Character Force Field inconstant (Constant Force) 

### ISSUE THREAD

**Issue by LewisSnow** [Frooxius/NeosPublic#427]
So, after the recent update to the force fields, there is now a issue where it wont affect a user reliably.
       We narrowed it down to the "Constant Force" Force Mode, Once a user has been affected by a force field once they wont be able to be affected by the same force field anymore, even after rejoining or respawning. 

Demo Vid (The force field being used here is set to "Constant Force" as the Force mode" with default values)
https://youtu.be/-j2aP0IUmik

[Update] Just tested it with "ConstantVelocity"
It also breaks with the "ConstantVelocity" force mode. So this would mean any "ConstantX" Force mode are having the issues.

**Comment by shiftyscales** [comment]
In addition to the above, we tested with an existing force field object- the Sonic spring. After the first use, any subsequent attempts to use the force field while the `ForceMode` is set to `ConstantForce` or `ConstantVelocity` will not affect the player.

**Comment by Frooxius** [comment]
Can you send me logs from any such attempt?

**Comment by Frooxius** [comment]
Should be fixed in 2020.3.14.776, thanks for the log and report!

**Comment by LewisSnow** [comment]
The Force fields still have that issue even after the recent patch
