### ISSUE TITLE
Bugs with Slot Children Events node

### ISSUE THREAD

**Issue by Zyzyl** [Frooxius/NeosPublic#666]
OnChildAdded and OnChildRemoved impulses do not fire if either Local User or Host User nodes are connected to the OnUser input. Tested in my cloud home so both output my user. Impulses fire as expected when no input node is connected to OnUser. According to @H3BO3 this may simply be inconsistent behaviour rather than a binary issue. 

The index of the slot given by the ChildAdded output is reported as -1 if the check occurs in an impulse chain initiated by the OnChildAdded output (checked with Get Child Index).

Edit: Similarly the slot name is reported as null if done similarly via Get Slot Name. The slot is correctly written to a slot variable however.

**Comment by Frooxius** [comment]
What configuration are you using this in? Were you alone in the world or were there other users? Was the user that was adding/removing children the same one as plugged into the input?

**Comment by H3BO3** [comment]
I did some of my own testing with this in the same setup - brand new world, no matter what was plugged in the behavior seemed very inconsistent. I was the only user there. However, when I was first trying to use it in another session with users it would not fire properly either, specifically when it was watching a parenting spawn point for new users

**Comment by TehTurk** [comment]
This bug I can also attest to this too, the SlotEvents does not like any user input whatsoever. I remember I would have host user and the events would still act up, or even active user and I was host.

**Comment by Zyzyl** [comment]
@Frooxius I was alone in the world, no others even AFK or had ever joined. I was using VR not desktop.

**Comment by Anomalous** [comment]
I noticed similar behavior from OnChildAdded, to the point that I gave up on using that node. In a self-hosted world as the only user, plug any user (local user, host user, etc) into the user input and it would never fire. Leave the user blank and it would work for a while, and then just quit working at some point. Creating a new OnChildAdded node would have it working again for a while, until it decided to quit.

This may be an unrelated problem, but I'll mention it anyway as I saw it occur in conjunction with the OnChildAdded node. I was trying to move newly spawned items to a specific slot, so I had the OnChildAdded monitoring the slot containing the user(s) and moving any detected child to a different slot, with a filter to ignore the user(s) themselves. This broke things in all sorts of ways, including creating undeletable slots. There were some interesting errors in the logs which I shared with Shifty, but those were judged to be not useful without further testing and qualifying the issue, which I haven't had time to do yet. This could be relevant in case monitoring the slot containing users creates some unexpected interactions that don't occur in less-busy slots.

**Comment by Frooxius** [comment]
@Anomalous Do you have any logs from when the node randomly stopped working? That seems like a really strange behavior, it's likely some exception during the firing. I have a hunch on what it might be, but log could help a lot.

**Comment by Frooxius** [comment]
Should be all fixed in 2020.6.10.647, thanks!

**Comment by Zyzyl** [comment]
Reopening this as I found the issue with checking the index of the Child output during an impulse chaing started by OnChildAdded is still present. Everything else seems to have been fixed though.

**Comment by Anomalous** [comment]
I suspect that the child index being -1 during OnChildAdded is working as intended. I had a discussion with Frooxius about this a couple weeks ago because I was trying to re-parent the child during on OnChildAdded event, which did not work, and he had this to say:
> Oh I see what it is. It seems that you made the object change its parent in response to the ChildAdded event. Problem with that is that the reason the event is being called in the first place is because it's in the middle of the parent being changed, so changing it again is blocked.

>It's a bit tricky situation. One solution is to wait a little bit (like a frame) before making the change or restructure the behavior so this situation is avoided in the first place.

If OnChildAdded occurs in the middle of the object's parent being changed, it makes sense that it doesn't have an index under the new parent yet.

**Comment by TehTurk** [comment]
That would make sense too considering you want to use SCE as a way of knowing when something is parented or deparented and what actions that you'd be able to do in that type of scenario.

**Comment by Zyzyl** [comment]
Yeah I guessed the -1 may be due to the slot being mid-reparent. The current behaviour will rarely be seriously problematic given the slot index is generally most useful as a way to find slots in the first place - a requirement mostly obviated by being provided with the reference directly from ChildAdded. 

That said, I first noticed this behaviour in a situation where each child under the 'watched slot' represented a bit of UI (elements in a UIX Vertical Layout). These each had a Text component on a sub-child which displayed the slot index +1 and the purpose of using SCE was to make them recalculate the displayed number if a slot was added/destroyed. In that context whenever a new UI piece was added its displayed number was showing up as 0 (-1 +1) rather than the expected value. Easily fixed by delaying the index check by a frame, but this serves as an existence proof that the current behaviour can cause issues.

**Comment by TehTurk** [comment]
Well the thing is when you add a child to a slot, it's expected to be at the end, or the start of the children count?  Typically it'll be added to the end so it's confusing to check the index of a slot when it's just being reparented. I agree it may not be too inuitive, but it also might just be understanding data structure thing. In cases like this you'd want to set the index as it's added then have it reflect what your doing because neos will swap or assign from memory however it's organized.

**Comment by Zyzyl** [comment]
For more context, in the situation I described above I was firing a dynamic impulse off of OnChildAdded and OnChildRemoved which targeted the Vertical Layout slot and caused each UI element to check its own index. This was the simplest way of doing the recalculation that I could think of which would work for an arbitrary number of slots and where any specific slot could be destroyed at any time.

Changing the current behaviour isn't something I require, as noted I found an easy workaround. However I'd recommend making a change if there is a relatively easy fix - generally I think it would be best to minimize how much users need to know how Neos works under the hood.

**Comment by H3BO3** [comment]
Hello @Frooxius , I wanted to ask a question regarding this node since I requested certain features on it before I knew more about how events and impulses actually worked - What exactly does the user input on the node do?

**Comment by Zyzyl** [comment]
This issue seems to have been fixed as of build 2020.9.14.511 so I'm closing this it - specifically "The index of the slot given by the ChildAdded output is reported as -1 if the check occurs in an impulse chain initiated by the OnChildAdded output (checked with Get Child Index)."
